### ISSUE TITLE
Object.create(null) benchmark request

### ISSUE THREAD

**Issue by anonrig** [RafaelGSS/nodejs-bench-operations#14]
```
function Empty() { }
Empty.prototype = Object.create(null)
```

Object.create(null) vs. new Empty() comparison

**Comment by RafaelGSS** [comment]
Would you like to send a Pull Request to address this issue? I'd also include the old fashioned `function Empty(); new Empty()`

**Comment by anonrig** [comment]
I just opened a pull request, but I'm open to suggestions on the benchmark names.

**Comment by anonrig** [comment]
I just opened a pull request, but I'm open to suggestions on the benchmark names. @RafaelGSS
