### ISSUE TITLE
Regression Checker

### ISSUE THREAD

**Issue by RafaelGSS** [RafaelGSS/nodejs-bench-operations#19]
Now that this repository store benchmark results for the last 3 versions of each active release line, we could create a regression checker to identify regressions between major, minor, and patch releases.

**Comment by H4ad** [comment]
Hey, here's my plan to support this:

Now we cache and run every benchmark report, we can:

- Also cache the JSON of the results of each benchmark, as long as the .md file.
  - We can also try to create a parser to extract from .md to not store too much information on the repository.
- Based on those values, we can create a GitHub action to combine and generate a report of those data grouped by:
  - Charts/Tables to show the difference between minor versions
  - Charts/Tables to show the difference between major versions

Let me know what are your thoughts on this, I can try to open a PR in the next weeks.

**Comment by RafaelGSS** [comment]
+1.
