### ISSUE TITLE
Split Github Actions by benchmark

### ISSUE THREAD

**Issue by H4ad** [RafaelGSS/nodejs-bench-operations#32]
Instead of having 1 benchmark for each node environment, I think running one Github Action for each benchmark could be better.

You can test all the node versions by changing it with `asdf` or `nvm`, in this way, I think it will run the benchmarks much faster, and also, saves some resources by not running a benchmark that was not affected by a new PR.

The only drawback I think is we should commit the benchmark result as json/md to grab that result of every benchmark and then create the concatenated version with all benchmarks.

Also, I think this could help to create the regression checker, since we run the regression check during this benchmark easily.

**Comment by RafaelGSS** [comment]
This is not possible nowadays. I'm using a single dedicated machine to perform the benchmark, if we split it into other actions we'll increase the chance of randomizations.

**Comment by H4ad** [comment]
But if we do not run more than 1 github action per time, I think it will be like running just one single action for every benchmark, or I'm missing something?

If you wanna try, I can create the github action for just one benchmark and see if change the values too much.

**Comment by RafaelGSS** [comment]
> But if we do not run more than 1 github action per time, I think it will be like running just one single action for every benchmark, or I'm missing something?

I don't understand. Regardless of how many actions will run, we should only run one benchmark per time, which means the time will not reduce. If we have 3 actions in the queue or just one action we'll still need to wait for a synchronous flow.

**Comment by H4ad** [comment]
It will take the same time to run all the benchmarks for the first time, and for the newly added benchmarks, it will only run that benchmark that was added/modified, so it might be easier and faster to add new benchmarks instead of just having the time increase linearly (10~20s for each new benchmark).

I think it could be more scalable to have 1 github action per benchmark, to run all nodejs versions, instead of having 1 github action per nodejs version to run all benchmarks. Still synchronous, but if I create a PR to add a new benchmark, I can add another action to run just that benchmark instead of running all the benchmarks, so it takes less time.

We'll just need another action to run after each benchmark to get all the cached data and then mount `README.md`.

**Comment by RafaelGSS** [comment]
> It will take the same time to run all the benchmarks for the first time, and for the newly added benchmarks, it will only run that benchmark that was added/modified, so it might be easier and faster to add new benchmarks instead of just having the time increase linearly (10~20s for each new benchmark).
> 
> I think it could be more scalable to have 1 github action per benchmark, to run all nodejs versions, instead of having 1 github action per nodejs version to run all benchmarks. Still synchronous, but if I create a PR to add a new benchmark, I can add another action to run just that benchmark instead of running all the benchmarks, so it takes less time.
> 
> We'll just need another action to run after each benchmark to get all the cached data and then mount `README.md`.

It works under the following circumstances:

* If we don't switch the dedicated machine
* For `X.0.0` versions.

I mean, I'm happy to accept a PR if that allows overriding the cached data by a parameter (workflow_dispatch). But I think it's too much work for a subtle improvement. If you want to do that, go ahead
