### ISSUE TITLE
Object.assign VS spread operator

### ISSUE THREAD

**Issue by H4ad** [RafaelGSS/nodejs-bench-operations#34]
Can we change the name of this benchmark to `Shallow Copy`?

I was thinking in add the comparison of using `Object.keys + for loop` to maybe create a new issue on NodeJS performance to change the implementation of [getHeaders](https://github.com/nodejs/node/blob/abb1c45af774ae3caaa449ddcbfe44143a98e9c7/lib/_http_outgoing.js#L755-L767) to use `spread operator`.

**Comment by H4ad** [comment]
Hm... I think we can create another test called shallow copy instead, is will be better than changing this benchmark.

**Comment by H4ad** [comment]
Actually, `getHeaders` is not 1-1 cloned because it performs some modifications in the final object :/

Anyway, at least one more benchmark.

**Comment by RafaelGSS** [comment]
> I was thinking in add the comparison of using Object.keys + for loop to maybe create a new issue on NodeJS performance to change the implementation of [getHeaders](https://github.com/nodejs/node/blob/abb1c45af774ae3caaa449ddcbfe44143a98e9c7/lib/_http_outgoing.js#L755-L767) to use spread operator.

This doesn't seem applicable to this repository. It's a specific usage and what you can do is fork and include that benchmark in your branch and share it.

Am I missing something?

**Comment by H4ad** [comment]
@RafaelGSS I was just thinking in change that benchmark to have enough evidence to suggest a change on `getHeaders`, but is not applicable since that method does not do a shallow copy.

I will close this issue since is out of scope from that initial idea and just leave https://github.com/RafaelGSS/nodejs-bench-operations/pull/35 since it can be good to have in this repo.
