### ISSUE TITLE
Generate graphs from results

### ISSUE THREAD

**Issue by RafaelGSS** [RafaelGSS/nodejs-bench-operations#4]
As titled

**Comment by AugustinMauroy** [comment]
You propose to use SVG ?

**Comment by RafaelGSS** [comment]
That would be great, yeah

**Comment by AugustinMauroy** [comment]
Can I propose a design ?

**Comment by RafaelGSS** [comment]
I gave a shot and I didn't like the result :P https://github.com/RafaelGSS/nodejs-bench-operations/pull/269
