### ISSUE TITLE
Adjust blob benchmark

### ISSUE THREAD

**Issue by RafaelGSS** [RafaelGSS/nodejs-bench-operations#47]
https://github.com/RafaelGSS/nodejs-bench-operations/actions/runs/6289574580/job/17076277995

Shared runners are too limited in terms of heap memory, we should reduce the memory allocation for this specific benchmark

**Comment by H4ad** [comment]
We can also create some fallbacks to not block other benchmarks, in this way, we at least save some resources and time.

**Comment by H4ad** [comment]
@RafaelGSS It's not a memory issue, is a bug actually haha.

If you try to run in that specific node version, it crashes.
If you use another one, like 20.5.0, if will run without taking too much memory.
