### ISSUE TITLE
Update node versions

### ISSUE THREAD

**Issue by Fdawgs** [RafaelGSS/nodejs-bench-operations#53]
First off, thanks for continuing to maintain this @RafaelGSS and @H4ad, I reference it quite a bit when looking to make optimisations in my own code.

The latest versions of Node 18 and 20 versions are not being benched.
Can these be updated?

Likewise, with Node 16 being EOL, is it worth benchmarking various versions of it, or would just using the last release, 16.20.2, be sufficient?

Happy to make a PR for this!

**Comment by RafaelGSS** [comment]
Yeah, let's update 18 and 20 and keep 16.20.2 and 16.0.0 for reference

**Comment by H4ad** [comment]
First, let me fix the issue with metadata (for regression checker) that we are having right know and then we can run one time and then remove these Node versions from the benchmarks.
