### ISSUE TITLE
Store ops/sec and samples only

### ISSUE THREAD

**Issue by RafaelGSS** [RafaelGSS/nodejs-bench-operations#60]
We only need to store `ops/sec` and `samples` for simpler regression checks.

cc: @H4ad

**Comment by H4ad** [comment]
Why samples? Samples are usually a large array of numbers which represents the metric of each run, if you need error mean, you can get from stats.

Also, adding samples could make the MD large again.

**Comment by H4ad** [comment]
Oh, okay, just the number of samples not the full samples.

Currently, we are storing these values:
https://github.com/RafaelGSS/nodejs-bench-operations/blob/1698ff64bdb02190f6100f9fded15710589f38cc/common.js#L56-L67

I will open a PR to add samples.
Do you want me to change `hz` to `opsSec` and remove the other fields?

**Comment by RafaelGSS** [comment]
Yes, that would be great. If we need other fields we can add them later.
