### ISSUE TITLE
Add various `startsWith` and `endsWith` alternatives

### ISSUE THREAD

**Issue by gurgunday** [RafaelGSS/nodejs-bench-operations#69]
[Reference](https://perf.link/#eyJpZCI6ImQwcmZtemtvNHQwIiwidGl0bGUiOiJGaW5kaW5nIG51bWJlcnMgaW4gYW4gYXJyYXkgb2YgMTAwMCIsImJlZm9yZSI6ImNvbnN0IGRhdGEgPSBbLi4uQXJyYXkoMTAwMCkua2V5cygpXS50b1N0cmluZygpXG5jb25zdCB0ZXN0ID0gJ3dvd19ncmVhdF9odWg%2FJyIsInRlc3RzIjpbeyJuYW1lIjoiVGVzdCBDYXNlIiwiY29kZSI6ImRhdGEuc3RhcnRzV2l0aCh0ZXN0KSIsInJ1bnMiOls3MzYwMDAsMjQxMzAwMCwxMzgzMDAwLDQ0NTYwMDAsNTgxMDAwLDIzODAwMDAsMTM4MzAwMCwxNjk1MDAwLDIxMDAwLDE1ODUwMDAsMjU0MDAwMCw0MjI1MDAwLDQ2OTEwMDAsNDI4MDAwLDI4NzIwMDAsMjY2OTAwMCwzMDcyMDAwLDQ5ODYwMDAsMjMxODAwMCwyOTg1MDAwLDEzNTUwMDAsMjA5ODAwMCw1MDQ3MDAwLDEyNDgwMDAsMjk0NDAwMCwyNzgwMDAsNDg0MzAwMCwyNDM3MDAwLDc5MTAwMCwzNTA3MDAwLDEzODMwMDAsMTgwMzAwMCw2MDA3MDAwLDI2NDAwMCw1NjIxMDAwLDc3MjkwMDAsMjQ1MzAwMCwyNzUwMDAsMTY4NDAwMCwxNDgzMDAwLDUwNDIwMDAsODUyMDAwLDIwNjMwMDAsMzYyMDAwMCwyNjAzMDAwLDgzMDAwMCwyMzM5MDAwLDYyMDAwMDAsMTk1MDAwMCw3NDYyMDAwLDEwMDAsMzk1MDAwLDEwMTIwMDAsMzM5OTAwMCwxMzgzMDAwLDQwNzkwMDAsMzg0MDAwMCwyOTEzMDAwLDM3OTQwMDAsNDI1NzAwMCwyOTQ1MDAwLDQ0NzYwMDAsNDM4OTAwMCw0Nzk2MDAwLDU5NDMwMDAsNDkwMDAsNTMxOTAwMCwxODM5MDAwLDE4MjEwMDAsNjgwMDAsNDk1MzAwMCw1MjE2MDAwLDMzMTYwMDAsMTY3NDAwMCw0NDA5MDAwLDg4NzAwMCwyNTk1MDAwLDEzNDcwMDAsMTM4MzAwMCwxNDIwMDAwLDIzMTgwMDAsMzE1NjAwMCwxMzgzMDAwLDE4MzkwMDAsNDIyNTAwMCwxMzgzMDAwLDE5MTIwMDAsNDE5MDAwLDIwMjQwMDAsMTcyMzAwMCwxNTczMDAwLDE2OTgwMDAsMTI1NjAwMCw0MDczMDAwLDEwMDgwMDAsNTkwMjAwMCwxMjQwMDAwLDEzODMwMDAsMTkwMTAwMCwyMzE0MDAwXSwib3BzIjoyNjAyNzgwfSx7Im5hbWUiOiJUZXN0IENhc2UiLCJjb2RlIjoiZGF0YS5zbGljZSgwLCB0ZXN0Lmxlbmd0aCkgPT09IHRlc3QiLCJydW5zIjpbMTIyMTAwMCw1MzU1MDAwLDE3MzkwMDAsNzgzMjAwMCwxMjIxMDAwLDIxMTEwMDAsNTMwMDAwLDE0MjAwMDAsNzI4MzAwMCwxNjI5MDAwLDUyOTIwMDAsNTYwMjAwMCwyMjUwMDAwLDEyMjEwMDAsMTc5NDAwMCwzMTA1MDAwLDMxODYwMDAsMjg0MTAwMCw0MDIxMDAwLDM4MDkwMDAsOTc2MDAwLDI3MzIwMDAsNzQ0MDAwMCwxNDM5MDAwLDIyOTUwMDAsNDc0NTAwMCw1OTAxMDAwLDMzNTcwMDAsNDU3NTAwMCwyMTYwMDAwLDEyODcwMDAsMjQ4MTAwMCw3OTUwMDAsNTczODAwMCwyMTc2MDAwLDU2ODIwMDAsMjk1NTAwMCw1Mjc1MDAwLDEyMjEwMDAsMjQ5OTAwMCw2Mzg3MDAwLDk4ODAwMCwxMjU0MDAwLDY5OTUwMDAsNDYwMTAwMCw2MTYwMDAsNjc3ODAwMCw4MjkzMDAwLDM1ODkwMDAsNzY0NTAwMCw0NDc4MDAwLDEwNzUwMDAsMTIyMTAwMCwzNzQxMDAwLDk1MjAwMCw5MDk3MDAwLDMzNDEwMDAsMzYzODAwMCwyMjgwMDAwLDM5MzYwMDAsMzA4NTAwMCwzNDY3MDAwLDQ0MjIwMDAsNTkzODAwMCw1MjI2MDAwLDM4MDUwMDAsNzAxNzAwMCwyMzU0MDAwLDExMTUwMDAsMTgwMDAsOTI4NTAwMCw2Mzc1MDAwLDUzMjgwMDAsNTgxNzAwMCw1MDYxMDAwLDg0MDUwMDAsMzUyMjAwMCwxMjIxMDAwLDEyMjEwMDAsNzgzMDAwLDMzMzYwMDAsMzM4ODAwMCwyMTAwMDAwLDIyODUwMDAsMzU0MTAwMCwyNDQ0MDAwLDEyMjEwMDAsNTI5MDAwLDE2NTIwMDAsMjIxOTAwMCwxMzg4MDAwLDI3NjgwMDAsMTIyMTAwMCwzODM4MDAwLDQyNDAwMCw2MDMzMDAwLDM1NjMwMDAsMTM1MTAwMCwzMTk5MDAwLDM1MDYwMDBdLCJvcHMiOjM0MzU2NzB9LHsibmFtZSI6IkZpbmQgaXRlbSA0MDAiLCJjb2RlIjoiZGF0YS5lbmRzV2l0aCh0ZXN0KSIsInJ1bnMiOlsxMDY5MDAwLDgwNDAwMCwxMzgzMDAwLDQ3MDAwMDAsMTk4NDAwMCwxMzgzMDAwLDMxNTAwMCw4NzgwMDAsNDY3NjAwMCwxNTcwMDAwLDE2ODEwMDAsNDQ1ODAwMCw3NTAwMCwxMDM0MDAwLDE4OTcwMDAsMjIzODAwMCwyNTAyMDAwLDI1ODQwMDAsNDg1OTAwMCwyOTkxMDAwLDEzODMwMDAsMTc2MDAwLDI5MjkwMDAsMTM4MzAwMCw0OTQ2MDAwLDU0OTgwMDAsNDI3MTAwMCwyMjEzMDAwLDQwMzYwMDAsMTY1NDAwMCwxMzgzMDAwLDQ5ODkwMDAsMzE4NjAwMCwxOTM2MDAwLDQxOTAwMDAsNzI3NTAwMCwxODM5MDAwLDEzODMwMDAsMTQ2NjAwMCwxODE5MDAwLDI2NTMwMDAsMTM4MzAwMCwxMTkyMDAwLDQ0MTEwMDAsMjQ5OTAwMCwyOTg1MDAwLDQyNTIwMDAsMjE4MDAwMCw1MzAxMDAwLDY2MTgwMDAsMTM4MjAwMCw2MTA4MDAwLDExODEwMDAsMjQxMDAwMCwxMzg0MDAwLDIwMTkwMDAsMjk4MzAwMCw0NjU5MDAwLDEzODMwMDAsMjQzODAwMCwzMDA4MDAwLDQ1OTMwMDAsMjYzMzAwMCwyODU2MDAwLDUwMDgwMDAsMTM4MzAwMCwyMzIzMDAwLDE0NzMwMDAsNDUwODAwMCwyODUyMDAwLDUwOTkwMDAsNDUzMjAwMCw3ODcwMDAsMjgwODAwMCwyNzc0MDAwLDMyODMwMDAsMjE1MjAwMCwxMjczMDAwLDEyNjAwMDAsMjgyNTAwMCwxMzgzMDAwLDEzODMwMDAsMjM0MTAwMCwxNzIyMDAwLDEwMTMwMDAsNzYzMDAwLDEzODMwMDAsMjgwMDAwLDE2OTIwMDAsMTI2NTAwMCw1MDAwLDEyOTkwMDAsODg2MDAwLDM2NjMwMDAsMjUyNjAwMCwzNjg0MDAwLDQwMDEwMDAsMjI1MDAwLDE3MjkwMDAsMTM4MzAwMF0sIm9wcyI6MjUwNTEzMH0seyJuYW1lIjoiRmluZCBpdGVtIDgwMCIsImNvZGUiOiJkYXRhLmxlbmd0aCA%2BPSB0ZXN0Lmxlbmd0aCAmJiBkYXRhLnNsaWNlKC10ZXN0Lmxlbmd0aCkgPT09IHRlc3QiLCJydW5zIjpbNjgwNDAwMCwxMDczMDAwLDE3MzkwMDAsNzgzMjAwMCw0NjQ2MDAwLDMyMTgwMDAsNjU3MDAwMCwxNjAwMCw3MTQ5MDAwLDE3MDAwMDAsNDU2NDAwMCwxMDQ2MDAwLDg4NDAwMDAsMTAwMTQwMDAsMTE0ODAwMCwxMDczMDAwLDEyNTAwMDAsODA0ODAwMCwyODIwMDAwLDM1MzgwMDAsMTI0OTAwMCw5MTUwMDAsNTEyNTAwMCwxMDg0MDAwLDYyNDUwMDAsNzAwMTAwMCw4MjgwMDAsNDIwNTAwMCw2NDkyMDAwLDczMDAwMCw4Mzc3MDAwLDE1ODYwMDAsNDU1OTAwMCwxODQ0MDAwLDY4ODQwMDAsMTEyMzQwMDAsMzAxNjAwMCw3MjU2MDAwLDE3MzcwMDAsMjk5MzAwMCwxMDczMDAwLDEwNzMwMDAsMjQ1ODAwMCw1NjUzMDAwLDc4MDMwMDAsNTI4MTAwMCw2NDkyMDAwLDc5NDEwMDAsMzM0NTAwMCw4MzYwMDAwLDU3MzUwMDAsOTQ2NDAwMCwxMDczMDAwLDQ3ODAwMDAsMTYwNzAwMCw0OTUyMDAwLDcxMzkwMDAsMTUwMDAsMzAxMTAwMCwyNTI0MDAwLDE1OTEwMDAsMzUzOTAwMCwxNDUyMDAwLDQ5ODQwMDAsNDQxNjAwMCwyMjY0MDAwLDUxMDkwMDAsMTQzOTAwMCwxMDczMDAwLDE5NDcwMDAsODI2NDAwMCw2NjM1MDAwLDE2MDAwMCwzMzQ0MDAwLDQ4NzAwMCwzMDI0MDAwLDM1NjAwMDAsODQyMzAwMCwwLDE3MDYwMDAsNzAzMTAwMCwyMDc4MDAwLDEyMDcwMDAsMTA3MzAwMCwxMDczMDAwLDEyMzEwMDAsNTI2MDAwLDU3MDYwMDAsMTA1MzAwMCw5MTEwMDAwLDI3MzkwMDAsMTA3MzAwMCwxMDczMDAwLDE3NTgwMDAsNzEwMDAwLDEwOTAwMDAsNjgwNzAwMCwxMTYyMDAwLDEwNjcwMDAsMTA3MzAwMF0sIm9wcyI6MzY4Mjg0MH1dLCJ1cGRhdGVkIjoiMjAyNC0wNC0yM1QxMjoxODoxNy42NTNaIn0%3D)

`slice` is super optimized, so much so that it's currently beating startsWith, I don't know why this is still the case, but until startsWith is optimized enough, we should track it in my opinion

**Comment by RafaelGSS** [comment]
Feel free to include the test here
