### ISSUE TITLE
`replace(//g)` vs `replaceAll()` benchmark

### ISSUE THREAD

**Issue by Fdawgs** [RafaelGSS/nodejs-bench-operations#7]
As titled, would be interesting to see the difference between the two!

**Comment by Fdawgs** [comment]
Requires node >= 15.0.0, and this repo tests with node 14. 😞

**Comment by RafaelGSS** [comment]
You can add it. Just skip this benchmark in the v14. Something like:

```js
if (semver.lt('15.0.0')) {
  console.log(H2('Header name'))
  console.log('This feature is not supported in this Node.js version')
  process.exit(0)
}
```
